# Generated by Django 4.2.13 on 2024-07-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='autumn',
            field=models.CharField(blank=True, choices=[('-', '-'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3b+', '3Б+')], max_length=3, null=True, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='spring',
            field=models.CharField(blank=True, choices=[('-', '-'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3b+', '3Б+')], max_length=3, null=True, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='levels',
            name='summer',
            field=models.CharField(blank=True, choices=[('-', '-'), ('1a', '1A'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б'), ('3b+', '3Б+')], max_length=3, null=True, verbose_name='Лето'),
        ),
    ]
