# Generated by Django 4.2.13 on 2024-07-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passage', '0005_alter_images_options_alter_passage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('pending', 'в работе'), ('accepted', 'принята'), ('rejected', 'отклонена')], default='new', max_length=8),
        ),
    ]
