# Generated by Django 4.2.11 on 2024-03-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mac', '0002_author_alter_productorder_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
